<?php

use Krystal\Form\Element;

?>
<form data-group="answer">
    <div class="well">
        <?php echo Element::hidden('id', $answer->getId()); ?>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Answer'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('answer[title]', $answer->getTitle(), array('class' => 'form-control', 'placeholder' => 'Target answer')); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('answer[category_id]', $categories, $answer->getCategoryId(), array('class' => 'form-control')); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('answer[order]', $answer->getOrder(), array('class' => 'form-control', 'placeholder' => 'Order of this answer to be displayed in a category')); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::checkbox('answer[published]', $answer->getPublished(), array('class' => 'form-control')); ?>
            </div>
        </div>
    </div>
    
    <?php if (!$answer->getId()): ?>
    <button data-button="add" data-back-url="<?php echo $this->url('Polls:Admin:Answer:Edit@indexAction', null); ?>" data-url="<?php echo $this->url('Polls:Admin:Answer:Add@addAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
    
    <?php else: ?>
    <button data-button="save" data-url="<?php echo $this->url('Polls:Admin:Answer:Edit@updateAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    
    <?php endif; ?>
    
    <button data-button="cancel" data-url="<?php echo $this->url('Polls:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    
</form>
