<?php

use Krystal\Form\Element;
use Krystal\Widget\GridWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
         <li><a href="<?php echo $this->url('Polls:Admin:Answer@addAction', $categoryId); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new answer'); ?></a></li>
         <li><a href="<?php echo $this->url('Polls:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add new category'); ?></a></li>
         <li class="divider"></li>
         <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
         
         <?php if(!empty($answers)): ?>
         <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Polls:Admin:Answer@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Polls:Admin:Answer@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
         
         <?php else: ?>
         <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
         
         <?php endif; ?>
      </ul>
    </div>
</div>

<form>
    <div class="row">
        <div class="col-lg-6">
            <h4><i class="fa fa-bar-chart"></i> <?php $this->show('Answers'); ?> (<?php echo count($answers); ?>)</h4>

            <div class="table-responsive">
                <?= $this->widget(new GridWidget($answers, array(
                    // A column to be considered as a primary key
                    'pk' => 'id',
                    'batch' => true,
                    'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                    'columns' => array(
                        array(
                            'column' => 'id',
                            'label' => '#'
                        ),

                        array(
                            'column' => 'title'
                        ),

                        array(
                            'column' => 'order',
                            'value' => function($answer){
                                return Element::number(sprintf('order[%s]', $answer->getId()), $answer->getOrder(), array('class' => 'form-control', 'min' => '0'));
                            }
                        ),

                        array(
                            'column' => 'published',
                            'value' => function($answer){
                                return Element::checkbox(sprintf('published[%s]', $answer->getId()), $answer->getPublished());
                            }
                        ),

                        array(
                            'column' => 'votes'
                        )
                    ),

                    'actions' => array(
                        'edit' => function($answer){
                            return Icon::edit(
                                $this->url('Polls:Admin:Answer@editAction', $answer->getId()),
                                $this->translate('Edit this answer')
                            );
                        },

                        'remove' => function($answer){
                            return Icon::remove(
                                $this->url('Polls:Admin:Answer@deleteAction', $answer->getId()), 
                                $this->translate('Remove this answer')
                            );
                        }
                    )
                ))); ?>
                
                <?php if (empty($answers)): ?>
                <div class="center-block">
                    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No answers'); ?></h2>
                </div>
                <?php endif; ?>

                <?php $this->loadPartial('paginator'); ?>
            </div>
        </div>
        
        <div class="col-lg-6">
            <div class="table-responsive">
                <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>

                <div class="table-responsive">
                    <?= $this->widget(new GridWidget($categories, array(
                        'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                        'rowAttributes' => array(
                            'class' => function($category) use ($categoryId){
                                return $category->getId() == $categoryId ? 'info' : null;
                            }
                        ),
                        'columns' => array(
                            array(
                                'column' => 'id',
                                'label' => '#'
                            ),

                            array(
                                'column' => 'name',
                                'translateable' => true,
                                'value' => function($category){
                                    return $category->getActive() ? 'Yes' : 'No';
                                }
                            ),

                            array(
                                'column' => 'active',
                                'translateable' => true,
                                'value' => function($category){
                                    return $category->getActive() ? 'Yes' : 'No';
                                }
                            ),

                            array(
                                'column' => 'options_count',
                                'label' => 'Amount of answers'
                            )
                        ),

                        'actions' => array(
                            'reset' => function($category){
                                return Icon::reset(
                                    $this->url('Polls:Admin:Answer@resetVotesAction', $category->getId()),
                                    $this->translate('Reset votes count'),
                                    $this->translate('Do you really want to reset votes count in this category?')
                                );
                            },
                            
                            'edit' => function($category){
                                return Icon::edit(
                                    $this->url('Polls:Admin:Category@editAction', $category->getId()),
                                    $this->translate('Edit this category')
                                );
                            },

                            'remove' => function($category){
                                return Icon::remove(
                                    $this->url('Polls:Admin:Category@deleteAction', $category->getId()), 
                                    $this->translate('Remove this category')
                                );
                            }
                        )
                    ))); ?>
                    
                    <?php if (empty($categories)): ?>
                    <div class="center-block">
                        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</form>
