<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            $this->url('Polls:Admin:Answer@addAction', $categoryId) => 'Add new answer',
            'Polls:Admin:Category@addAction' => 'Add new category'
        ),

        'actions' => array(
            'data' => $answers,
            'save' => 'Polls:Admin:Answer@tweakAction',
            'delete' => 'Polls:Admin:Answer@deleteAction'
        )
    )); ?>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><?php $this->show('Answers'); ?> (<?php echo count($answers); ?>)</h4>
            </div>

            <form>
                <div class="table-responsive">
                    <?= $this->widget(new GridViewWidget($answers, array(
                        'pk' => 'id',
                        'batch' => true,
                        'tableClass' => 'table table-hover table-bordered table-striped',
                        'columns' => array(
                            array(
                                'column' => 'id',
                                'label' => '#'
                            ),

                            array(
                                'column' => 'title'
                            ),

                            array(
                                'column' => 'order',
                                'value' => function($answer){
                                    return Element::number(sprintf('order[%s]', $answer->getId()), $answer->getOrder(), array('class' => 'form-control', 'min' => '0'));
                                }
                            ),

                            array(
                                'column' => 'published',
                                'value' => function($answer){
                                    return Element::checkbox(sprintf('published[%s]', $answer->getId()), $answer->getPublished());
                                }
                            ),

                            array(
                                'column' => 'votes'
                            )
                        ),

                        'actions' => array(
                            'edit' => function($answer){
                                return Icon::edit(
                                    $this->url('Polls:Admin:Answer@editAction', $answer->getId()),
                                    $this->translate('Edit this answer')
                                );
                            },

                            'remove' => function($answer){
                                return Icon::remove(
                                    $this->url('Polls:Admin:Answer@deleteAction', $answer->getId()), 
                                    $this->translate('Remove this answer')
                                );
                            }
                        )
                    ))); ?>
                    
                    <?php if (empty($answers)): ?>
                    <div class="center-block">
                        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No answers'); ?></h2>
                    </div>
                    <?php endif; ?>

                    <?php $this->loadPartial('paginator'); ?>
                </div>
            </form>
        </div>
    </div>
    
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>
            </div>

            <div class="table-responsive">
                <?= $this->widget(new GridViewWidget($categories, array(
                    'tableClass' => 'table table-hover table-bordered table-striped',
                    'rowAttributes' => array(
                        'class' => function($category) use ($categoryId){
                            return $category->getId() == $categoryId ? 'table-info' : null;
                        }
                    ),
                    'columns' => array(
                        array(
                            'column' => 'id',
                            'label' => '#'
                        ),

                        array(
                            'column' => 'name'
                        ),

                        array(
                            'column' => 'active',
                            'translateable' => true,
                            'value' => function($category){
                                return $category->getActive() ? 'Yes' : 'No';
                            }
                        ),

                        array(
                            'column' => 'options_count',
                            'label' => 'Amount of answers'
                        )
                    ),

                    'actions' => array(
                        'reset' => function($category){
                            return Icon::reset(
                                $this->url('Polls:Admin:Answer@resetVotesAction', $category->getId()),
                                $this->translate('Reset votes count'),
                                $this->translate('Do you really want to reset votes count in this category?')
                            );
                        },
                        
                        'edit' => function($category){
                            return Icon::edit(
                                $this->url('Polls:Admin:Category@editAction', $category->getId()),
                                $this->translate('Edit this category')
                            );
                        },

                        'remove' => function($category){
                            return Icon::remove(
                                $this->url('Polls:Admin:Category@deleteAction', $category->getId()), 
                                $this->translate('Remove this category')
                            );
                        }
                    )
                ))); ?>

                <?php if (empty($categories)): ?>
                <div class="center-block">
                    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
