<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;
use Krystal\Form\HtmlHelper;

?>

<div class="btn-toolbar">
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
         <li><a href="<?php echo $this->url('Polls:Admin:Answer@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new answer'); ?></a></li>
         <li><a href="<?php echo $this->url('Polls:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add new category'); ?></a></li>
         <li class="divider"></li>
         <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
         
         <?php if(!empty($answers)): ?>
         <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Polls:Admin:Answer@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Polls:Admin:Answer@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
         
         <?php else: ?>
         <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
         
         <?php endif; ?>
      </ul>
    </div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Polls')); ?>

<form>
    <div class="row">
        <div class="col-lg-6">
            <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Options'); ?> (<?php echo count($answers); ?>)</h4>
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped table-condensed">
                    <thead>
                        <tr>
                            <th class="text-center">
                                <?php if (!empty($answers)): ?>
                                <input type="checkbox" />
                                <?php endif; ?>
                            </th>
                            <th class="text-center"><?php $this->show('#'); ?></th>
                            <th class="text-center"><?php $this->show('Title'); ?></th>
                            <th class="text-center"><?php $this->show('Order'); ?></th>
                            <th class="text-center"><?php $this->show('Published'); ?></th>
                            <th class="text-center"><?php $this->show('Actions'); ?></th>
                        </tr>
                    </thead>
                    
                    <?php if (!empty($answers)): ?>
                    <tbody>
                        <?php foreach ($answers as $answer): ?>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="toDelete[<?php echo $answer->getId(); ?>]" />
                            </td>
                            <td class="text-center text-muted"><?php echo $answer->getId(); ?></td>
                            <td class="text-center"><?php echo $answer->getTitle(); ?></td>
                            <td class="text-center col-lg-2">
                                <?php echo Element::number(sprintf('order[%s]', $answer->getId()), $answer->getOrder(), array('class' => 'form-control', 'min' => '0')); ?>
                            </td>
                            <td class="text-center">
                                <?php echo Element::checkbox(sprintf('published[%s]', $answer->getId()), $answer->getPublished()); ?>
                            </td>
                            <td class="text-center">
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this option'); ?>" data-button="edit" href="<?php echo $this->url('Polls:Admin:Answer@editAction', $answer->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this option'); ?>" data-button="delete" href="#" data-url="<?php echo $this->url('Polls:Admin:Answer@deleteAction', $answer->getId()); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <?php endif; ?>
                </table>
                
                <?php if (empty($answers)): ?>
                <div class="center-block">
                    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No answers'); ?></h2>
                </div>
                <?php endif; ?>
                
                <?php $this->loadPartial('paginator'); ?>
            </div>
        </div>
        
        <div class="col-lg-6">
            <div class="table-responsive">
                <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                                <th class="text-center"><?php $this->show('#'); ?></th>
                                <th class="text-center"><?php $this->show('Name'); ?></th>
                                <th class="text-center"><?php $this->show('Amount of answers'); ?></th>
                                <th class="text-center"><?php $this->show('Actions'); ?></th>
                            </tr>
                        </thead>
                        
                        <?php if (!empty($categories)): ?>
                        <tbody>
                            <?php foreach ($categories as $category): ?>
                            <tr class="<?php echo HtmlHelper::addOnDemand(isset($categoryId) && $categoryId == $category->getId(), 'success'); ?>">
                                <td class="text-center text-muted"><?php echo $category->getId(); ?></td>
                                <td class="text-center">
                                    <a href="<?php echo $this->url('Polls:Admin:Browser@categoryAction', $category->getId()); ?>">
                                        <?php echo $category->getName(); ?>
                                    </a>
                                </td>
                                <td class="text-center"><?php echo $category->getOptionsCount(); ?></td>
                                <td class="text-center">
                                    <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this category'); ?>" data-button="edit" href="<?php echo $this->url('Polls:Admin:Category@editAction', $category->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this category'); ?>" data-button="delete" data-url="<?php echo $this->url('Polls:Admin:Category@deleteAction', $category->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                        <?php endif; ?>
                    </table>
                    
                    <?php if (empty($categories)): ?>
                    <div class="center-block">
                        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</form>
