<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>
<form data-group="category">
    <div class="well clearfix">
        <?php echo Element::hidden('category[id]', $category->getId()); ?>

        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('category[name]', $category->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Category name'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>

        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Class'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('category[class]', $category->getClass(), array('class' => 'form-control', 'placeholder' => $this->translate('Class name to be used when rendering on site'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Active'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::checkbox('category[active]', $category->getActive(), array('class' => 'form-control')); ?>
            </div>
        </div>
    </div>

    <?php if (!$category->getId()): ?>
    <button data-button="add" data-back-url="<?php echo $this->url('Polls:Admin:Category@editAction', null); ?>" data-url="<?php echo $this->url('Polls:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    
    <?php else: ?>
    <button data-button="save" data-url="<?php echo $this->url('Polls:Admin:Category@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>

    <?php endif; ?>
    <button data-button="cancel" data-url="<?php echo $this->url('Polls:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    
</form>
