<form>
    <div class="well">
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Answer'); ?><b>*</b></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <input type="text" name="title" class="form-control" placeholder="<?php echo $this->translate('Target answer'); ?>" />
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Category'); ?></label>
            <div class="col-lg-10">
                <select name="categoryId" class="form-control">
                    <option value="1">None</option>
                    
                    <?php foreach($categories as $category): ?>
                    <option value="<?php echo $category->id; ?>"><?php echo $category->name; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Order'); ?><b>*</b></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <input type="text" name="order" class="form-control" placeholder="<?php echo $this->translate('Order of this answer to be displayed in a category'); ?>" />
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Published'); ?><b>*</b></label>
            <div class="col-lg-10">
                <input type="hidden" name="published" value="0" />
                <input type="checkbox" name="published" value="1" class="form-control" checked="checked" />
            </div>
        </div>
    </div>
    
    <?php $this->loadBlock('end'); ?>
    
    <button type="submit" id="add-btn" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> <?php echo $this->translate('Add'); ?></button>
    <button type="submit" id="add-create-btn" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> <?php echo $this->translate('Add & Create new'); ?></button>
    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-floppy-remove"></span> <?php echo $this->translate('Cancel'); ?></button>
    
</form>
