<?php

use Krystal\Form\Element;

?>
<form>
    <div class="well">
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Answer'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('title', $option->getTitle(), array('class' => 'form-control', 'placeholder' => 'Target answer')); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('categoryId', $categories, $option->getCategoryId(), array('class' => 'form-control')); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Order'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('order', $option->getOrder(), array('class' => 'form-control', 'placeholder' => 'Order of this answer to be displayed in a category')); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Published'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::checkbox('published', $option->getPublished(), array('class' => 'form-control')); ?>
            </div>
        </div>
    </div>
    
    <button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
    <button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    
</form>
