<?php

use Krystal\Form\Element;

?>
<form>
    <div class="well">
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Answer'); ?><b>*</b></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('title', $option->getTitle(), array('class' => 'form-control', 'placeholder' => 'Target answer')); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('categoryId', $categories, $option->getCategoryId(), array('class' => 'form-control')); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Order'); ?><b>*</b></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('order', $option->getOrder(), array('class' => 'form-control', 'placeholder' => 'Order of this answer to be displayed in a category')); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php echo $this->translate('Published'); ?><b>*</b></label>
            <div class="col-lg-10">
                <?php echo Element::checkbox('published', $option->getPublished(), array('class' => 'form-control')); ?>
            </div>
        </div>
    </div>
    
    <button type="submit" id="add-btn" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> <?php echo $this->translate('Add'); ?></button>
    <button type="submit" id="add-create-btn" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> <?php echo $this->translate('Add & Create new'); ?></button>
    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-floppy-remove"></span> <?php echo $this->translate('Cancel'); ?></button>
    
</form>
